# Generated by Django 5.0.1 on 2024-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
