# Generated by Django 5.0.1 on 2024-01-08 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_hospital_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PC', 'Primary Check'), ('C', 'Consultation'), ('D', 'Discharged'), ('A', 'Admitted'), ('R', 'Referred')], max_length=2)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospital')),
            ],
        ),
    ]
