# Generated by Django 5.0.1 on 2024-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_hospital_name_alter_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
