# Generated by Django 5.0.1 on 2024-01-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_remove_patient_age_patient_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='department',
            field=models.ManyToManyField(to='hospitalapp.department'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
